akm_article:
    resource: "@AkmArticleBundle/Resources/config/routing.yml"
    prefix:   /

akmhello:
    resource: "@AkmhelloBundle/Resources/config/routing.yml"
    prefix:   /

# Internal routing configuration to handle ESI
#_internal:
#    resource: "@FrameworkBundle/Resources/config/routing/internal.xml"
#    prefix:   /_internal
