parameters:
#    akmhello.example.class: Akm\helloBundle\Example

services:
#    akmhello.example:
#        class: %akmhello.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
