parameters:
#    akm_article.example.class: Akm\ArticleBundle\Example

services:
#    akm_article.example:
#        class: %akm_article.example.class%
#        arguments: [@service_id, "plain_value", %parameter%]
